version: '3.8'

services:
  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-5.0.4
    environment:
      DB_SERVER_HOST: postgres-database
      POSTGRES_DB: zabbix-server
      POSTGRES_USER: zabbix-server
      POSTGRES_PASSWORD: zabbix-server
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Warsaw
    networks:
      - zabbix-stack
    depends_on:
      - zabbix-server
      - postgres-database
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ubuntu-5.0.4
    environment:
      DB_SERVER_HOST: postgres-database
      POSTGRES_DB: zabbix-server
      POSTGRES_USER: zabbix-server
      POSTGRES_PASSWORD: zabbix-server
      ZBX_DEBUGLEVEL: 1
      ZBX_TIMEOUT: 5
    networks:
      - zabbix-stack
  postgres-database:
    container_name: postgres-database
    image: postgres:13
    environment:
      POSTGRES_DB: zabbix-server
      POSTGRES_USER: zabbix-server
      POSTGRES_PASSWORD: zabbix-server
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - zabbix-stack
    depends_on:
      - zabbix-server
networks:
  zabbix-stack:
    ipam:
      config:
        - subnet: 172.20.10.0/24

volumes:
  postgres-data: